/*
 * Stoatworks Labs - About window data for Afterglow.
 *
 * GENERATED by stoatworks-backend/scripts/sync-about.py. Do not edit: the next
 * sync overwrites it. The facts come from the website's projects.json, which
 * is the one place they are written down.
 *
 * ---------------------------------------------------------------- EXCEPT
 *
 * This one was hand-written, in the generated shape, because afterglow is not
 * in projects.json yet and is not in sync-about.py's TARGETS yet. Adding it to
 * projects.json PUBLISHES a page on stoatworks-labs.com, which is a decision
 * about the outside world rather than about this repo, so it has not been
 * made here. Until it is:
 *
 *   - `guide` and `page` are deliberately EMPTY, so the About block shows no
 *     "User guide" or "Project page" button. StoatworksAboutLinks.h leaves an
 *     absent link out of the list rather than offering a button that 404s.
 *   - the next real sync will overwrite this file and add both buttons.
 *
 * See docs/NOTES.md.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "Afterglow";
    inline constexpr auto slug = "afterglow";
    inline constexpr auto hook = "Decaying frame trails for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/afterglow";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
